services:
  - type: web
    name: virtual-mall-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m pip install --force-reinstall -r requirements.txt && python -m gunicorn --bind 0.0.0.0:$PORT app:app